image: alpine:latest

stages:
  - prepare
  - build
  - deploy
  - teardown

# The deployment on aws depends on thre main environment variables
# AWS_ACCESS_KEY_ID       create at https://console.aws.amazon.com/iam/
# AWS_SECRET_ACCESS_KEY   create at https://console.aws.amazon.com/iam/
# AWS_DEFAULT_REGION      default:eu-central-1
variables:
  BUILD_PATH: "web/build"
  IMAGE_NAME: "frontend"                                   # docker image base name
  IMAGE_PATH: "$DOCKER_REGISTRY/$DOCKER_ORGANISATION/$IMAGE_NAME:$CI_COMMIT_REF_SLUG"
  DOCKER_REGISTRY_REPOSITORY_ID: "717423"                  # https://gitlab.com/api/v4/projects/12894267/registry/repositories/
  EC2_INSTANCE_NAME: mlreef-$CI_COMMIT_REF_SLUG            # environment name and url are set separately
  EC2_PROVISION_SCRIPT: "./bin/provision.sh"
  STARTUP_SCRIPT: "bin/startup.sh"
  DEPLOY_SCRIPT:  "bin/deploy.sh"
  DOCKER_COMPOSE: docker-compose.yml                       # file for transmitting VM information between stages
  INSTANCE_INFO:  instance.info                            # file for transmitting VM information between stages


provision-ec2:
  stage: prepare
  image: registry.gitlab.com/systemkern/s5:latest-aws
  variables:
    EC2_MACHINE_SIZE:  "t3a.medium"                        # https://aws.amazon.com/ec2/instance-types/
    EC2_IMAGE_AMI:     "ami-050a22b7e0cf85dd0"             # ubuntu 16.04 LTS
    EC2_SECURITY_GRP:  "application_servers"
  before_script:
    - chmod 400 development_deployment.pem                 # prepare private key file
    - bin/decomission.sh $EC2_INSTANCE_NAME                # first shutdown all current instances
    - sed -i "s~master/bin~$CI_COMMIT_REF_NAME/bin~"       $STARTUP_SCRIPT
    - sed -i "s~AWS_ACCESS_KEY_ID=XXXXX~AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID~"                 $STARTUP_SCRIPT
    - sed -i "s~AWS_SECRET_ACCESS_KEY=XXXXX~AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY~"     $STARTUP_SCRIPT
    - cat $STARTUP_SCRIPT
  script:
    - INSTANCE=$($EC2_PROVISION_SCRIPT $EC2_INSTANCE_NAME $STARTUP_SCRIPT)
    - echo "$INSTANCE"
    - echo "$INSTANCE" | tr -d '\r' > $INSTANCE_INFO       # pass instance url to deploy stage
  after_script:
    - cat $INSTANCE_INFO
    - if [ $INSTANCE == "null" ]; then exit 1;  fi         # error on invalid INSTANCE_INFO
  artifacts:
    paths:
      - "$INSTANCE_INFO"                                   # pass the file which contains our instance URL
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $CI_PIPELINE_URL                                  # temporary url will be corrected by the gitlab-env-conf job
    on_stop: decomission                                   # clean up after branch merge


build-frontend:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login ${DOCKER_REGISTRY} -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
  script:
    - cd web
    - rm -rf package-lock.json
    - rm -rf node_modules
    - echo "creating docker image ${IMAGE_NAME} for user ${DOCKER_USER}"
    - docker build --pull --tag "$IMAGE_PATH" -f Dockerfile .
    - docker push "${IMAGE_PATH}"


# This job adds the actual frontend URL to the Environments GUI in gitlab.com
gitlab-env-conf:
  image: registry.gitlab.com/systemkern/s5:latest
  stage: deploy
  variables:
    KEY: "Authorization:"                                  # workaround to preserver the yaml structure
    GITLAB_PORT: 10080
  before_script:
    - URL=$(cat $INSTANCE_INFO)
    - echo $URL                                            # debug output
    - chmod 400 development_deployment.pem                 # prepare private key file
    - chmod +x $DEPLOY_SCRIPT
    # rewrite deploy script to include the correct url
    - sed -i "s~http://gitlab:80~http://$URL:$GITLAB_PORT~"    $DEPLOY_SCRIPT
    - sed -i "s/frontend:master/frontend:$CI_COMMIT_REF_SLUG/" $DOCKER_COMPOSE
  script:
    - $DEPLOY_SCRIPT $URL $IMAGE_PATH
    - echo "========= ========== ========== =========="
    # Get the ID of the gitlab environment we want to edit
    - ID=$(curl --header "$KEY Bearer $GITLAB_API_TOKEN"
      https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/environments?name=$CI_COMMIT_REF_SLUG
      | jq -c '.[] | select(.name | contains("'$CI_REF_SLUG'")) | .id'
      )
    - echo "ID is $ID"                                      # debug output
    # configure the gitlab environment with the correct URL
    - curl --request PUT --header "$KEY Bearer $GITLAB_API_TOKEN"
      --data "name=$CI_COMMIT_REF_SLUG&external_url=http://$URL"
      https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/environments/$ID


decomission:
  when: manual
  image: registry.gitlab.com/systemkern/s5:latest-aws
  stage: teardown
  variables:
    GIT_STRATEGY: none
    # Workaround for Gitlab Bug https://gitlab.com/gitlab-org/gitlab-runner/issues/1809
    WORKAROUND: "PRIVATE-TOKEN:" # workaround to not break the yaml structure
  script:
    # use the aws-cli to retrieve the description (json) for our machine
    # parse the json with jq to get the instance id
    # the xargs command at the end submits the termination command to AWS
    - aws ec2 describe-instances
      --filters "Name=tag:Name,Values=$EC2_INSTANCE_NAME"
      | jq -r ".Reservations[].Instances[].InstanceId"
      | xargs --no-run-if-empty aws ec2 terminate-instances
      --instance-id
    - curl --request DELETE --header "$WORKAROUND $GITLAB_API_TOKEN"
      https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/$DOCKER_REGISTRY_REPOSITORY_ID/tags/$CI_COMMIT_REF_SLUG
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop
  except:
    refs:
      - master
