image: gradle:latest

stages:
  - build
  - deploy


kotlin2js:
  stage: build
  script:
    - ./gradlew clean build deployJs     # deployJs copies the js modules to web/…/kotlin
  artifacts:
    paths:
      - web/src/main/web/kotlin


pages:
  stage: deploy
  script:
    - mkdir public                       # create deploy directory
    - cp -r web/src/main/web/* public/       # deploy static files
    - ls -al public
  artifacts:
    paths:
    - public
#  only:
#    - master
