include:
  - local: .gitlab-ci-provision.yml
  - local: .gitlab-ci-build.yml
  - local: .gitlab-ci-deploy.yml
  - local: .gitlab-ci-test.yml
  - local: .gitlab-ci-maintenance.yml

stages:
  - stage1
  - stage2
  - deploy
  - test
  - maintenance

# The deployment on aws depends on three main environment variables
# AWS_ACCESS_KEY_ID       create at https://console.aws.amazon.com/iam/
# AWS_SECRET_ACCESS_KEY   create at https://console.aws.amazon.com/iam/
# AWS_DEFAULT_REGION      default:eu-central-1
# GITLAB_API_TOKEN        for creating and deleting environments on gitlab.com
variables:
  BACKEND_IMAGE_PATH:   "$DOCKER_REGISTRY/$DOCKER_ORGANISATION/$BACKEND_IMAGE_NAME:$BACKEND_TAG"
  INSTANCE_INFO:        "out/instance.info"                # file for transmitting VM information between stages
  S3_DATA_BUCKET:       "mlreef-application-data"          # see also ec2 startup script
  DATA_ARCHIVE:         "mlreef-data-develop.zip"
  # GATSBY_PATH_PREFIX:   "/frontend"                      # fix links for mlreef.gitlab.io/frontend

.except-docu-branches:
  except:
    variables:
      # $CI_COMMIT_REF_NAME is the complete branch name e.g. "feature/my-cool-new-branch"
      - $CI_COMMIT_REF_NAME =~ /^doc\//                    # match every branch "doc/**"
      - $CI_COMMIT_REF_NAME =~ /^docs\//                   # match every branch "docs/**"
      - $CI_COMMIT_REF_NAME =~ /^docu\//                   # match every branch "docu/**"
      - $CI_COMMIT_REF_NAME =~ /^documentation\//          # match every branch "documentation/**"
      - $CI_COMMIT_REF_NAME =~ /^site\//                   # match every branch "site/**"

.feature-branches-only:
  extends: [".except-docu-branches"]
  except:
    refs:
      - develop
      - master
  except:
    changes:
      - "*.md"                                         # skip the pipeline for documentation changes
      - "*.txt"



pages:
  stage: deploy
  only:
    changes:
      - docs/**/*
      - README.md
  image: node:10.19.0-alpine                                # https://hub.docker.com/_/node/
  cache:
    key: mlreef-documentation-npm-cache
    paths:
      - /usr/local/lib/node_modules
      - docs/node_modules
  script: bin/ci-pages
  artifacts:
    paths:
      - public


smoke test suite:
  extends: [.except-docu-branches]
  stage: test
  when: delayed
  start_in: 4 minutes
  image: registry.gitlab.com/systemkern/s5:latest-newman
  cache:
    key: newman
    paths:
      - node_modules/.bin/
  script: bin/ci-smoke-tests

experiment test suite:
  extends: [.except-docu-branches]
  when: delayed
  stage: test
  start_in: 4 minutes
  image: registry.gitlab.com/systemkern/s5:latest
  script: bin/ci-test-end2end-experiment
