# DOCKER_HUB_USER
# DOCKER_HUB_PASSWORD
variables:
  DOCKER_HUB_ORGANISATION: "camillopachmann"
  IMAGE_NAME: "eps"

before_script:
  - echo "creating docker image $IMAGE_NAME for organisation $DOCKER_HUB_ORGANISATION"
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"

build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  variables:
    TAG: "latest"
    IMAGE_PATH: "$DOCKER_HUB_ORGANISATION/$IMAGE_NAME:$TAG"
  #before_script: # this will completly override the global before_script
  services:
    - docker:dind
  script:
    - docker build --pull --tag "$IMAGE_PATH" executable-pipeline-framework/mvp/
    - docker push "$IMAGE_PATH"
  only:
    - master

build:
  # Official docker image.
  image: docker:latest
  stage: build
  variables:
    TAG: "nightly"
    IMAGE_PATH: "$DOCKER_HUB_ORGANISATION/$IMAGE_NAME:$TAG"
  services:
    - docker:dind
  #before_script: # this will completly override the global before_script
  script:
    - docker build --pull --tag "$IMAGE_PATH" executable-pipeline-framework/mvp/
    - docker push "$IMAGE_PATH"
  except:
    - master
