include:
  - local: .gitlab-ci-provision.yml
  - local: .gitlab-ci-build.yml
  - local: .gitlab-ci-deploy.yml
  - local: .gitlab-ci-maintenance.yml

stages:
  - provision
  - build
  - deploy
  - maintenance

# The deployment on aws depends on three main environment variables
# AWS_ACCESS_KEY_ID       create at https://console.aws.amazon.com/iam/
# AWS_SECRET_ACCESS_KEY   create at https://console.aws.amazon.com/iam/
# AWS_DEFAULT_REGION      default:eu-central-1
# GITLAB_API_TOKEN        for creating and deleting environments on gitlab.com
variables:
  FRONTEND_IMAGE_NAME:  "frontend"                         # docker image base name
  FRONTEND_TAG:         "$CI_COMMIT_REF_SLUG"              # must be the same as "tag" in in FRONTEND_IMAGE_PATH
  # unfortunately using the $FRONTEND_TAG variable inside the FRONTEND_IMAGE_PATH does not work
  FRONTEND_IMAGE_PATH:  "$DOCKER_REGISTRY/$DOCKER_ORGANISATION/$FRONTEND_IMAGE_NAME:$CI_COMMIT_REF_SLUG"
  BACKEND_IMAGE_NAME:   "backend"                          # docker image base name
  BACKEND_TAG:          "latest"
  BACKEND_IMAGE_PATH:   "$DOCKER_REGISTRY/$DOCKER_ORGANISATION/$BACKEND_IMAGE_NAME:$BACKEND_TAG"
  DOCKER_REGISTRY_REPO: "717423"                           # https://gitlab.com/api/v4/projects/12894267/registry/repositories/
  EC2_INSTANCE_NAME:    "mlreef-$CI_COMMIT_REF_SLUG"       # environment name and url are set separately
  SSH_KEYFILE:          "src/terraform/development.pem"
  DEVICE_MAPPINGS:      "src/resources/block-device-mappings.json"
  NGINX_CONFIG:         "src/resources/nginx_proxy.conf"
  STARTUP_SCRIPT:       "src/bin/startup.sh"
  GITLAB_SETUP:         "src/bin/setup-gitlab.sh"
  DEPLOY_SCRIPT:        "src/bin/deploy.sh"
  BACKUP_SCRIPT:        "src/bin/backup.sh"
  RESTORE_SCRIPT:       "src/bin/restore.sh"
  DOCKER_COMPOSE:       "docker-compose.yml"
  DOCKER_ENV:           ".env"
  INSTANCE_INFO:        "instance.info"                    # file for transmitting VM information between stages
  S3_DATA_BUCKET:       "mlreef-application-data"          # see also ec2 startup script
  DATA_ARCHIVE:         "mlreef-data-develop.zip"
