stages:
  - build
  - deploy
  - integration
  - teardown

build and test:
  stage: build
  services:
    - docker:19.03.0-dind
  image: java:8
  variables:
    REDIS_HOST: "redis"
    REDIS_PORT: 6379
    POSTGRES_DB: $DB_NAME
    POSTGRES_USER: $DB_USER
    POSTGRES_PASSWORD: $DB_PASSWORD
    DOCKER_HOST: "tcp://docker:2375"  # gitlab needs this to support docker testcontainers
    DOCKER_DRIVER: overlay2           # gitlab needs this to support docker testcontainers
    DOCKER_TLS_CERTDIR: ""            # "/certs" gitlab needs this to support docker testcontainers

  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew
    - echo "Use DB $DB_NAME with $DB_USER"
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script:
    - ./gradlew build
    - mkdir mlreef-rest/build/test-results/test/mlreef-domain
    - cp mlreef-domain/build/test-results/test/TEST-*.xml mlreef-rest/build/test-results/test/mlreef-domain/
    - ./gradlew jacocoTestReport coverageReport
    - ./gradlew :mlreef-rest:bootJar
    - ./gradlew :mlreef-rest:prepareDocker
  artifacts:
    paths:
      - mlreef-rest/build/asciidoc/html5/rest-api.html
      - mlreef-rest/build/libs/*
      - mlreef-rest/build/dependency/*
      - mlreef-rest/build/reports/jacoco/test
      - mlreef-rest/build/reports/tests/
    reports:
      junit: mlreef-rest/build/test-results/test/**/TEST-*.xml


deploy:
  stage: deploy
  services:
    - docker:19.03.0-dind
  image: docker:19.03.1
  script:
    - export TAG="${CI_COMMIT_REF_SLUG}"
    - if [ $CI_COMMIT_REF_SLUG == "master" ]; then TAG="latest";  fi          # follow docker naming conventions
    - echo "${CI_REGISTRY_PASSWORD}" | docker login ${CI_REGISTRY} --username=${CI_REGISTRY_USER} --password-stdin
    - cd mlreef-rest
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:$TAG" -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$TAG"


pages:
  stage: deploy
  cache:
    key: pages-public-cache
    paths:
      - public/
  script:
    - ls public/develop public/feature/* -l || echo "Still empty"
    - mkdir public/$CI_COMMIT_BRANCH -p || echo "Already existing"
    - rm public/$CI_COMMIT_BRANCH/* -R || echo "Still empty"
    - mkdir public/$CI_COMMIT_BRANCH/coverage -p
    - mv mlreef-rest/build/reports/jacoco/test/html/* public/$CI_COMMIT_BRANCH/coverage
    - mv mlreef-rest/build/asciidoc/html5/rest-api.html public/$CI_COMMIT_BRANCH/index.html
    - echo "Documentation URL is $CI_PAGES_URL/$CI_COMMIT_BRANCH"
  artifacts:
    paths:
      - public
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $CI_PAGES_URL/$CI_COMMIT_BRANCH
    on_stop: decommission

integration-test:
  stage: deploy
  services:
    - docker:19.03.0-dind
  image: java:8
  allow_failure: true
  variables:
    DOCKER_HOST: "tcp://docker:2375"  # gitlab needs this to support docker testcontainers
    DOCKER_DRIVER: overlay2           # gitlab needs this to support docker testcontainers
    DOCKER_TLS_CERTDIR: ""            # "/certs" gitlab needs this to support docker testcontainers
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew
    - echo "Use DB $DB_NAME with $DB_USER"
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script:
    - ./gradlew integrationTest

decommission:
  when: manual
  stage: teardown
  except:
    refs:
      - master
  image: registry.gitlab.com/systemkern/s5:latest-aws    # based on python:3-slim
  variables:
    GIT_STRATEGY: none
    COLON: ":" # workaround to preserve the yaml structure (because of the ":")
  cache:
    key: pages-public-cache
    paths:
      - public/
  before_script:
    # Require Gitlab API token or this job
    - if [ "$GITLAB_COM_API_TOKEN" = "" ]; then exit 1; fi
  script:
    # Get the registry repository ID from the Gitlab API
    - CONTAINER_REPO_ID=$(curl --silent --header "PRIVATE-TOKEN$COLON $GITLAB_COM_API_TOKEN"
      https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/
      | jq -r .[0].id
      )

    - curl --request DELETE --header "PRIVATE-TOKEN$COLON $GITLAB_COM_API_TOKEN"
      https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/$CONTAINER_REPO_ID/tags/$CI_COMMIT_REF_SLUG
    - rm public/$CI_COMMIT_BRANCH/* -R || echo "Gitlab page is already empty"
  artifacts:
    paths:
      - public
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop
