image: gradle:latest

stages:
  - build
  - deploy


#kotlin2js:
#  stage: build
#  script:
#    - ./gradlew clean build
#  artifacts:
#    paths:
#      - web/src/main/web/kotlin


npm-build:
  image: node:latest
  stage: build
  cache:
    paths:
      - web/node_modules      # cache externale node modules
  script:
    - cd web                  # switch to web module
    - npm install             # get npm up and running
    - npm run build
  artifacts:
    paths:
      - web/build/            # pass build output


pages:
  image: alpine:latest
  stage: deploy
  script:
    - mkdir public             # create deploy directory
    - cp -r web/build/* public # copy the react build to gitlab public pages
    - ls -al public
  artifacts:
    paths:
    - public
  only:
    - master
