# Variables provided by the repository
# DOCKER_USER
# DOCKER_PASSWORD
variables:
  DOCKER_REGISTRY: "registry.gitlab.com"
  DOCKER_ORGANISATION: "mlreef"
  IMAGE_NAME: "epf"

before_script:
  - echo "creating docker image ${IMAGE_NAME} for user ${DOCKER_USER}"
  - docker login ${DOCKER_REGISTRY} -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"


build-nightly:
  # official docker image.
  image: docker:latest
  stage: build
  variables:
    TAG: "nightly"
    IMAGE_PATH: "$DOCKER_REGISTRY/$DOCKER_ORGANISATION/$IMAGE_NAME:$TAG"
  services:
    - docker:dind
  #before_script: # this will completely override the global before_script
  script:
    - bin/build.sh
    - docker push "${IMAGE_PATH}"
  except:
    - master


build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  variables:
    TAG: "latest"
    IMAGE_PATH: "$DOCKER_REGISTRY/$DOCKER_ORGANISATION/$IMAGE_NAME:$TAG"
  #before_script: # this will completely override the global before_script
  services:
    - docker:dind
  script:
    - bin/build.sh
    - docker push "${IMAGE_PATH}"
  only:
    - master
