.base-test:
  extends: [.except-docu-branches]
  stage: smoke tests
  when: delayed
  start_in: 4 minutes
  before_script:
    - URL=$(cat $INSTANCE_INFO)
    - echo $URL                                            # debug output

.base-curl-test:
  extends: .base-test
  image: registry.gitlab.com/systemkern/s5:latest


# Runs a postman test suite
# docker run --rm --tty -v ${PWD}/src/test:/src/test registry.gitlab.com/systemkern/s5:newman newman run /src/test/mlreef-integration-tests.postman_collection.json --environment /src/test/postman_environment.json
postman test suite:
  extends: .base-test
  image: registry.gitlab.com/systemkern/s5:latest-newman
  cache:
    key: newman
    paths:
      - node_modules/.bin/
  variables:
    NEWMAN_ENV: "src/test/environment.json"
  script:
    # replace base url in postman environment file
    - sed -i "s/mlreef.com/$URL/" $NEWMAN_ENV
    - cat $NEWMAN_ENV
    - newman run src/test/smoke-tests.postman_collection.json --environment $NEWMAN_ENV


call gitlab api:
  extends: .base-curl-test
  # Gitlab Runners are a separate process from Gitlab's API and Gitlab's frontend
  script: if [ $(curl --silent --output /dev/null -w ''%{http_code}'' $URL/api/v4/projects) != 200 ]; then
      curl $URL/api/v4/projects
      exit 1;
    fi

