# Variables provided by the repository
# DOCKER_HUB_USER
# DOCKER_HUB_PASSWORD
variables:
  DOCKER_HUB_ORGANISATION: "camillopachmann"
  IMAGE_NAME: "mlreef-epf"

before_script:
  - echo "creating docker image $IMAGE_NAME for user $DOCKER_HUB_USER"
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"


build-nightly:
  # official docker image.
  image: docker:latest
  stage: build
  variables:
    TAG: "nightly"
    IMAGE_PATH: "$DOCKER_HUB_ORGANISATION/$IMAGE_NAME:$TAG"
  services:
    - docker:dind
  #before_script: # this will completely override the global before_script
  script:
    - bin/build.sh
    - docker push "$IMAGE_PATH"
  except:
    - master


build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  variables:
    TAG: "latest"
    IMAGE_PATH: "$DOCKER_HUB_ORGANISATION/$IMAGE_NAME:$TAG"
  #before_script: # this will completely override the global before_script
  services:
    - docker:dind
  script:
    - bin/build.sh
    - docker push "$IMAGE_PATH"
  only:
    - master
