include:
  - local: .gitlab/.base-gitlab-ci-docker-build.yml
  - local: backend/.gitlab-ci.yml
  - local: epf/.gitlab-ci.yml
  - local: nautilus/.gitlab-ci.yml
  - local: web/.gitlab-ci.yml

stages:
  - build
  - deploy
  - test
  - staging
  - maintenance

variables:
  S3_DATA_BUCKET:       "mlreef-application-data"          # see also ec2 startup script
  DATA_ARCHIVE:         "mlreef-data-master.zip"

.except-docu-branches:
  except:
    variables:
      # $CI_COMMIT_REF_NAME is the complete branch name e.g. "feature/my-cool-new-branch"
      - $CI_COMMIT_REF_NAME =~ /^doc\//                    # match every branch "doc/**"
      - $CI_COMMIT_REF_NAME =~ /^docs\//                   # match every branch "docs/**"
      - $CI_COMMIT_REF_NAME =~ /^docu\//                   # match every branch "docu/**"
      - $CI_COMMIT_REF_NAME =~ /^documentation\//          # match every branch "documentation/**"
      - $CI_COMMIT_REF_NAME =~ /^site\//                   # match every branch "site/**"


.only-on-code-changes: &run-on-all-code-changes
  only:
    changes:
      - backend/**/*
      - bin/ci-deploy
      - bin/install
      - bin/resources/runner-config*
      - epf/**/*
      - k8s/**/*
      - web/**/*
      - .gitlab-ci.yml
      - docker-compose.yml
.pages-code-changes: &run-on-pages-relevant-changes
  only:
    changes:
      - backend/**/*
      - docs/**/*
      - README.md

deploy_review:
  extends: [".except-docu-branches"]
  stage: deploy
  <<: *run-on-all-code-changes
  image:
    name: registry.gitlab.com/mlreef/devops/k8s-images/k8s-kubectl:latest
    entrypoint: ["/bin/bash", "-c"]
  except:
    - tags
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: stop_review
  script:
    - kubectl version
    - kubectl delete deploy,svc,ing,pod -l ref=${CI_ENVIRONMENT_SLUG}
    - ./k8s/gitlab-deployment
    - ./k8s/k8s_final_yml_deployment
    - sed_files deployment apps-${CI_ENVIRONMENT_SLUG}.yml
    - cat apps-${CI_ENVIRONMENT_SLUG}.yml
    - kubectl apply -f apps-${CI_ENVIRONMENT_SLUG}.yml
    - sleep 120
    - kubectl get deploy,svc,ing,pod -l ref="${CI_ENVIRONMENT_SLUG}"
    - kubectl get pvc -l ref="${CI_ENVIRONMENT_SLUG}"
    - kubectl describe ing -l ref="${CI_ENVIRONMENT_SLUG}"
    - echo $KUBE_NAMESPACE
  artifacts:
    paths:
      - out/instance.info             # pass instance url to later stages (see k8s/includes/ci-environment)

stop_review:
  image:
    name: registry.gitlab.com/mlreef/devops/k8s-images/k8s-kubectl:latest
    entrypoint: ["/bin/bash", "-c"]
  stage: maintenance
  variables:
    GIT_STRATEGY: none
  when: manual
  only:
    - branches
  except:
    - tags
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  script:
    - kubectl version
    - kubectl delete ing -l ref=${CI_ENVIRONMENT_SLUG}
    - kubectl delete all -l ref=${CI_ENVIRONMENT_SLUG}
    - kubectl delete pvc -l ref=${CI_ENVIRONMENT_SLUG}
    # remove the branch's docker containers
    # ?????? is the id of the "nautilus" repository id
    #- curl --request DELETE --header "PRIVATE-TOKEN:$GITLAB_COM_API_TOKEN"
    #  https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/??????/tags/$CI_COMMIT_REF_SLUG
    # 1117031 is the id of the "gateway's" sub-repository id
    - curl --request DELETE --header "PRIVATE-TOKEN:$GITLAB_COM_API_TOKEN"
      https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/1117031/tags/$CI_COMMIT_REF_SLUG
    # 1151242 is the id of the "backend's" sub-repository id
    - curl --request DELETE --header "PRIVATE-TOKEN:$GITLAB_COM_API_TOKEN"
      https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/1151242/tags/$CI_COMMIT_REF_SLUG
    # 1196730 is the id of the "epf's" sub-repository id
    - curl --request DELETE --header "PRIVATE-TOKEN:$GITLAB_COM_API_TOKEN"
      https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/registry/repositories/1196730/tags/$CI_COMMIT_REF_SLUG
    - kubectl delete namespace $KUBE_NAMESPACE

clean rest docs folder:
  extends: [.except-docu-branches]
  stage: maintenance
  <<: *run-on-pages-relevant-changes
  image: registry.gitlab.com/systemkern/s5:1
  allow_failure: true
  cache:
    key: pages-public-cache
    paths:
      - public/
      - /usr/local/lib/node_modules
      - docs/node_modules
  # See bin/ci-pages for the exact path to where rest docs are deployed
  script: |
    chmod +x docs/bin/ci-pages-cleanup
    docs/bin/ci-pages-cleanup


.helper_functions: &helper_functions_template |
  function sed_files() {
    file_type=${1:-compose}
    file_name=$2
    echo "File Type is $file_type"

    if [[ "$file_type" == "deployment" ]]
    then
      echo "Applying SED on Deployment Yamls"
      echo "CI_REGISTRY_IMAGE : ${CI_REGISTRY_IMAGE}"
      sed -i "s~__CI_REGISTRY_IMAGE__~${CI_REGISTRY_IMAGE}~" $file_name
      echo "CI_ENVIRONMENT_SLUG: ${CI_ENVIRONMENT_SLUG}"
      sed -i "s/__CI_ENVIRONMENT_SLUG__/${CI_ENVIRONMENT_SLUG}/" $file_name
      echo "CI_COMMIT_REF_SLUG: ${CI_COMMIT_REF_SLUG}"
      sed -i "s~__VERSION__~${CI_COMMIT_REF_SLUG}~" $file_name
      echo "CI_PROJECT_NAME: ${CI_PROJECT_NAME}"
      sed -i "s~__CI_PROJECT_NAME__~${CI_PROJECT_NAME}~" $file_name
      echo "CI_PROJECT_PATH_SLUG : ${CI_PROJECT_PATH_SLUG}"
      sed -i "s~__CI_PROJECT_PATH_SLUG__~${CI_PROJECT_PATH_SLUG}~" $file_name
      echo "KUBE_INGRESS_BASE_DOMAIN : ${KUBE_INGRESS_BASE_DOMAIN}"
      sed -i "s/__KUBE_INGRESS_BASE_DOMAIN__/${KUBE_INGRESS_BASE_DOMAIN}/" $file_name
    else
      echo "Applying SED on compose Yamls"
      sed -i "s~__CI_REGISTRY_IMAGE__~${CI_REGISTRY_IMAGE}~" docker-compose.yml
    fi
  }

before_script:
  - *helper_functions_template




# please do not move, adapt, delete, move to a include, whatever, if you did not read about the special "pages" job of gitlab ci
pages:
  image: node:10.19.0-alpine                                # https://hub.docker.com/_/node/
  stage: deploy
  <<: *run-on-pages-relevant-changes
  cache:
    key: pages-public-cache
    paths:
      - public/
      - /usr/local/lib/node_modules
      - docs/node_modules
  script: docs/bin/ci-pages
  artifacts:
    paths:
      - public

test rest docs are present:
  extends: [.except-docu-branches]
  stage: test
  <<: *run-on-pages-relevant-changes
  image: registry.gitlab.com/systemkern/s5:1
  allow_failure: true
  # See bin/ci-pages for the exact path to where rest docs are deployed
  script: |
    echo "Testing if backend rest-docs are available at https://mlreef.gitlab.io/mlreef/rest-api/$CI_COMMIT_BRANCH/index.html"
    echo "https://mlreef.gitlab.io/mlreef/rest-api/$CI_COMMIT_BRANCH/index.html"
    curl --fail --GET "https://mlreef.gitlab.io/mlreef/rest-api/$CI_COMMIT_BRANCH/index.html" > rest-docs-test.html
    ls -al

    # look for the specific error output of Spring Rest Docs
    #cat rest-docs-test.html | grep -e "not found for operation::" > missing.html
    #if [ -e missing.html ]; then
    #  cat missing.html  
    #  echo "MLReef rest-docs is missing some snippets :( "
    #  exit 1
    #fi
    #if [ -s missing.html ]; then
    #  echo "Yay, MLReef rest-docs is not missing snippets :) "
    #fi




smoke tests:
  extends: [.except-docu-branches]
  stage: test
  <<: *run-on-all-code-changes
  when: delayed
  start_in: 5 minutes
  image: registry.gitlab.com/systemkern/s5:latest-git
  script: bin/ci-smoke-tests


end2end tests:
  # import the centralised caching configuration for npm caches (from web/.gitlab-ci.yml)
  extends: [".except-docu-branches", ".npm-cache-config"]
  stage: test
  <<: *run-on-all-code-changes
  needs:
    - deploy_review                                   # wait for the deployment to be finished
  # The image should be the same image as web/Dockerfile and the "build frontend" job
  image: node:10.19.0-alpine
  allow_failure: true ##Temporary till the time bug gets fixed
  script: web/bin/ci-run-end2end-tests


.system-tests:
  extends: [".except-docu-branches"]
  <<: *run-on-all-code-changes
  except:
    refs:
      - master
  stage: test
  image: java:8
  services:
    - docker:19.03.0-dind
  cache:
    key: "$CI_COMMIT_BRANCH"
    paths:
      - .gradle/wrapper
      - .gradle/caches
  variables:
    DOCKER_HOST: "tcp://docker:2375"  # gitlab needs this to support docker testcontainers
    DOCKER_DRIVER: overlay2           # gitlab needs this to support docker testcontainers
    DOCKER_TLS_CERTDIR: ""            # "/certs" gitlab needs this to support docker testcontainers

system tests:
  extends: [".system-tests"]
  allow_failure: false
  stage: test
  when: delayed
  start_in: 3 minutes
  script: backend/bin/ci-system-tests

pipeline tests:
  extends: [".system-tests"]
  allow_failure: true
  stage: test
  when: manual
  script: backend/bin/ci-pipeline-tests



