image: gradle:latest

stages:
  - build
  - deploy
  - teardown

variables:
  BUILD_PATH: "web/build"
  BUCKET_NAME: mlreef-$CI_COMMIT_REF_SLUG   #environment name and url are set separately


npm-build:
  image: node:latest
  stage: build
  cache:
    paths:
      - web/node_modules      # cache externale node modules
  script:
    - cd web                  # switch to web module
    - npm install             # get npm up and running
    - npm run build
  artifacts:
    paths:
      - ${BUILD_PATH}         # pass build output


# The deployment on aws dependes on thre main environment variables
# AWS_ACCESS_KEY_ID       create at https://console.aws.amazon.com/iam/
# AWS_SECRET_ACCESS_KEY   create at https://console.aws.amazon.com/iam/
# AWS_DEFAULT_REGION      default:eu-central-1
deploy:
  image: registry.gitlab.com/systemkern/s5:latest-aws   # based on python:3-slim
  stage: deploy
  dependencies:
    - npm-build                      # explicit dependencies, to avoid confusion
  cache:
    key: mlreef-all-python-dependencies
    paths:
      - .cache/pip
      - venv/
  script:
    - aws s3api create-bucket --bucket ${BUCKET_NAME}
      --region ${AWS_DEFAULT_REGION}
      --create-bucket-configuration LocationConstraint=${AWS_DEFAULT_REGION}
      || echo "Bucket already existed" # ignore fail if bucket exists
    - create-aws-policy ${BUCKET_NAME}
    - aws s3api put-bucket-policy --bucket ${BUCKET_NAME}
      --no-confirm-remove-self-bucket-access
      --policy file://policy.json
    - aws s3 sync ${BUILD_PATH} s3://${BUCKET_NAME} --delete # upload new version
    - echo "Instance location https://${BUCKET_NAME}.s3.${AWS_DEFAULT_REGION}.amazonaws.com/index.html"
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://mlreef-${CI_COMMIT_REF_SLUG}.s3.${AWS_DEFAULT_REGION}.amazonaws.com/index.html  # This is the url of the bucket we saved before
    on_stop: undeploy       # clean up after branch merge


undeploy:
  when: manual
  image: python:3-slim
  stage: teardown
  variables:
    GIT_STRATEGY: none
  cache:
    key: mlreef-all-python-dependencies
    paths:
      - .cache/pip
      - venv/
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME} --recursive
    - aws s3api delete-bucket --bucket ${BUCKET_NAME}
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop
  except:
    refs:
      - master
      - develop
