.only-on-backend-code-changes:
  only:
    changes:
      - backend/mlreef-rest/src/**/*
      - backend/Dockerfile
      - backend/gradle.properties
      - backend/settings.gradle
      - backend/.gitlab-ci.yml


test backend:
  allow_failure: false
  extends: [".except-docu-branches", ".only-on-backend-code-changes"]
  stage: build
  image: java:8
  services:
    - docker:19.03.0-dind
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
    - backend/.gradle/wrapper
    - backend/.gradle/caches
  script: backend/bin/ci-test-backend
  artifacts:
    paths:
      - backend/mlreef-rest/build/
    reports:
      junit: backend/mlreef-rest/build/test-results/test/**/TEST-*.xml


build backend:
  extends: [".base-docker-build", ".only-on-backend-code-changes"]
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - backend/.gradle/wrapper
      - backend/.gradle/caches
  script: |
    docker build --tag "$BACKEND_IMAGE_PATH" -f backend/Dockerfile backend
    docker push "$BACKEND_IMAGE_PATH"
    if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
      BACKEND_LATEST_IMAGE_PATH=$(echo $BACKEND_IMAGE_PATH | sed 's/:\(.*\)$/:latest/')
      docker tag $BACKEND_IMAGE_PATH $BACKEND_LATEST_IMAGE_PATH
      docker push $BACKEND_LATEST_IMAGE_PATH
    fi


backend integration tests:
  extends: [".except-docu-branches", ".only-on-backend-code-changes"]
  needs: ["test backend"]
  allow_failure: true
  stage: test
  image: java:8
  services:
    - docker:19.03.0-dind
  cache:
    key: "$CI_COMMIT_BRANCH"
    paths:
      - .gradle/wrapper
      - .gradle/caches
  variables:
    DOCKER_HOST: "tcp://docker:2375"  # gitlab needs this to support docker testcontainers
    DOCKER_DRIVER: overlay2           # gitlab needs this to support docker testcontainers
    DOCKER_TLS_CERTDIR: ""            # "/certs" gitlab needs this to support docker testcontainers
  script: backend/bin/ci-integration-test-backend
