.only-on-backend-code-changes:
  only:
    changes:
      - backend/mlreef-domain/src/**/*
      - backend/mlreef-rest/src/**/*
      - backend/Dockerfile
      - backend/gradle.properties
      - backend/settings.gradle
      - backend/.gitlab-ci.yaml


test backend:
  extends: [".except-docu-branches", ".only-on-backend-code-changes"]
  stage: build
  image: java:8
  services:
    - docker:19.03.0-dind
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
    - backend/.gradle/wrapper
    - backend/.gradle/caches
  script: backend/bin/ci-test-backend
  artifacts:
    paths:
      - backend/mlreef-rest/build/
    reports:
      junit: backend/mlreef-rest/build/test-results/test/**/TEST-*.xml


build backend:
  extends: [".except-docu-branches", ".only-on-backend-code-changes"]
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.0-dind
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - backend/.gradle/wrapper
      - backend/.gradle/caches
  before_script:
    - export GATEWAY_IMAGE_PATH=$CI_REGISTRY_IMAGE/gateway:$CI_COMMIT_REF_SLUG
    - export BACKEND_IMAGE_PATH=$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG
    - export     EPF_IMAGE_PATH=$CI_REGISTRY_IMAGE/epf:$CI_COMMIT_REF_SLUG
  script: |
    backend/bin/ci-build-backend
    docker push "$BACKEND_IMAGE_PATH"


backend integration tests:
  extends: [".except-docu-branches", ".only-on-backend-code-changes"]
  needs: ["test backend"]
  allow_failure: true
  stage: test
  image: java:8
  services:
    - docker:19.03.0-dind
  cache:
    key: "$CI_COMMIT_BRANCH"
    paths:
      - .gradle/wrapper
      - .gradle/caches
  variables:
    DOCKER_HOST: "tcp://docker:2375"  # gitlab needs this to support docker testcontainers
    DOCKER_DRIVER: overlay2           # gitlab needs this to support docker testcontainers
    DOCKER_TLS_CERTDIR: ""            # "/certs" gitlab needs this to support docker testcontainers
  script: backend/bin/ci-integration-test-backend
