build epf:
  extends: [".base-docker-build"]
  only:
    changes:
      - epf/**/*
  script: |
    docker build --tag "$EPF_IMAGE_PATH" -f epf/Dockerfile epf
    docker push "$EPF_IMAGE_PATH"
    if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then 
      EPF_LATEST_IMAGE_PATH=$(echo $EPF_IMAGE_PATH | sed 's/:\(.*\)$/:latest/')
      docker tag $EPF_IMAGE_PATH $EPF_LATEST_IMAGE_PATH
      docker push $EPF_LATEST_IMAGE_PATH
    fi
