version: '3'
services:
  mlreef-rest:
    build: .
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
