# original source: https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml
version: '3'

services:

  backend:
    container_name: backend
    image: registry.gitlab.com/mlreef/backend:latest
    restart: always
    depends_on:
      - mlreef-postgres
      - redis
    ports:
      - "8080:8080"
      - "20080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_TEST_PRIVATE_TOKEN=${JAVA_TEST_PRIVATE_TOKEN:-mock-gitlab-token}  # secret, use ENV var
      - GITLAB_HOSTNAME=${GITLAB_HOSTNAME:-localhost:10080}
      - GITLAB_ADMIN_TOKEN=${GITLAB_ADMIN_TOKEN:?gitlab-admin-token-empty}            # secret, use ENV var
      - DB_HOST=mlreef-postgres
      - DB_PORT=6000
      - DB_USER=mlreef
      - DB_PASS=password                                  # secret, use ENV var
      - DB_NAME=mlreef_backend


  mlreef-postgres:
    container_name: mlreef-postgres
    restart: always
    image: sameersbn/postgresql:10-2
    ports:
      - "6000:5432"
    environment:
      - DB_USER=mlreef
      - DB_PASS=password                                  # secret, use ENV var
      - DB_NAME=mlreef_backend
      - DB_EXTENSION=pg_trgm


  redis:
    container_name: redis
    restart: always
    image: sameersbn/redis:4.0.9-2
    ports:
      - "6379:6379"


