logging:
  level:
    root: INFO
    com.mlreef.rest: DEBUG
    org.springframework.security: INFO
    org.springframework.orm: INFO
    org.hibernate: INFO

spring:
  devtools:
    add-properties: true
  jpa:
    show-sql: false # true for debuggin
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

mlreef:
  gitlab:
    rootUrl: ${GITLAB_ROOT_URL:http://localhost:10080}
    adminUserToken: ${GITLAB_ADMIN_TOKEN}
