logging:
  level:
    root: INFO
    com.mlreef.rest: DEBUG
    org.springframework.security: INFO
    org.springframework.orm: INFO
    org.hibernate: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %boldGreen([%thread]) %cyan(%logger{15}.%M [%line]) - %msg%n%throwable'

spring:
  devtools:
    add-properties: true
  jpa:
    show-sql: false # true for debugging
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

mlreef:
  gitlab:
    root-url: ${GITLAB_ROOT_URL:http://localhost:10080}
    admin-user-token: ${GITLAB_ADMIN_TOKEN}
