logging:
  level:
    root: INFO
    com.mlreef.rest: INFO
    org.springframework.security: WARN
    org.springframework.orm: WARN
    org.hibernate: WARN
#    org:
#      hibernate:
#        persister:
#          entity: DEBUG


mlreef:
  gitlab:
    root-url: ${GITLAB_ROOT_URL:http://localhost:10080}
    admin-user-token: ${GITLAB_ADMIN_TOKEN}
  epf:
    backend-url: ${EPF_BACKEND_URL:http://backend:8080}
    image-tag: ${EPF_IMAGE_TAG:latest}
