logging:
  level:
    root: INFO
    com.mlreef.rest: INFO
    org.springframework.security: WARN
    org.springframework.orm: WARN
    org.hibernate: WARN

mlreef:
  epf:
    backend-url: ${EPF_BACKEND_URL:http://backend:8080}
    gitlab-url: ${EPF_GITLAB_URL:http://gitlab:10080}
    image-tag: ${EPF_IMAGE_TAG:latest}
  gitlab:
    root-url: ${GITLAB_ROOT_URL}
    admin-user-token: ${GITLAB_ADMIN_TOKEN}
  bot-management:
    epf-bot-email-domain: mlreef.com
    epf-bot-password-length: 20
  security:
    gitlab-oauth: false

spring:
  devtools:
    add-properties: false
  data:
    repositories.type: none
    redis:
      repositories:
        enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:6000}/${DB_NAME:mlreef_backend}
    username: ${DB_USER:mlreef}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

