logging:
  level:
    root: INFO
    com.mlreef.rest: INFO
    org.springframework.security: WARN
    org.springframework.orm: WARN
    org.hibernate: WARN


mlreef:
  gitlab:
    rootUrl: ${GITLAB_ROOT_URL:http://localhost:10080}
    adminUserToken: ${GITLAB_ADMIN_TOKEN}
