logging:
  level:
    root: INFO
    com.mlreef.rest: DEBUG
    org.springframework.security: DEBUG

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

