logging:
  level:
    root: INFO
    com.mlreef.rest: DEBUG
    org.springframework.security: INFO
    org.springframework.orm: INFO
    org.hibernate: INFO
    web: DEBUG

spring:
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:7000}/${DB_NAME:mlreef_backend_dev}
    username: ${DB_USER:mlreef}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:7379}

mlreef:
  gitlab:
    rootUrl: ${GITLAB_ROOT_URL:http://localhost:10080}
    adminUserToken: ${GITLAB_ADMIN_TOKEN}
