spring:
  devtools:
    add-properties: true

mlreef:
  gitlab:
    rootUrl: ${GITLAB_ROOT_URL:http://localhost:10080}
    adminUserToken: ${GITLAB_ADMIN_TOKEN}
    mockUserToken: ${JAVA_TEST_PRIVATE_TOKEN:dev-mock-token}
