pages:
  stage: deploy
  only:
    changes:
      - docs/**/*
      - README.md
  image: node:10.19.0-alpine                                # https://hub.docker.com/_/node/
  cache:
    key: mlreef-documentation-npm-cache
    paths:
      - /usr/local/lib/node_modules
      - docs/node_modules
  script: bin/ci-pages
  artifacts:
    paths:
      - public