mlreef:
  epf:
    image-tag: ${EPF_IMAGE_TAG:latest}
    # When running in docker on a single machine, the EPF will access
    # the Backend via the docker internal hostname backend:8080
    # and Gitlab via the docker hostname gitlab:10080
    backend-url: ${EPF_BACKEND_URL}
    gitlab-url: ${GITLAB_ROOT_URL}
  gitlab:
    root-url: ${GITLAB_ROOT_URL}
    admin-user-token: ${GITLAB_ADMIN_TOKEN}
    admin-username: ${GITLAB_ADMIN_USERNAME:mlreef}
    admin-password: ${GITLAB_ADMIN_PASSWORD:password}
  bot-management:
    epf-bot-email-domain: mlreef.com
    epf-bot-password-length: 20
  security:
    gitlab-oauth: false
  scheduler:
    pool-size: 100
  email:
    send-attempts-on-fail: 5
    pause-between-failed-attempts-sec: 60
  password-management:
    reset-password-send-email-interval-sec: 300
    reset-password-token-valid-sec: 600
    password-reset-url: https://mlreef.com/login/password-reset
    password-reset-confirm-url: https://mlreef.com/api/v1/password/confirm
  proxy:
    enabled: ${PROXY_ENABLED:false}
    host: ${PROXY_HOST:localhost}
    port: ${PROXY_PORT:8866}


spring:
  devtools:
    add-properties: false
  data:
    repositories.type: none
    redis:
      repositories:
        enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:6000}/${DB_NAME:mlreef_backend}
    username: ${DB_USER:mlreef}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NOREPLY_EMAIL}
    password: ${NOREPLY_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %boldGreen([%thread]) %cyan(%logger{15}.%M [%line]) - %msg%n%throwable'


