mlreef:
  epf:
    backend-url: ${EPF_BACKEND_URL:http://backend:8080}
    gitlab-url: ${EPF_GITLAB_URL:http://gitlab:10080}

logging:
  level:
    root: INFO
    com.mlreef.rest: DEBUG
    web: INFO
    org.springframework.security: DEBUG
    org.springframework.orm: WARN
    org.hibernate: WARN
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.security.web.util.matcher.AndRequestMatcher: INFO
    org.springframework.security.web.util.matcher.AntPathRequestMatcher: INFO
    org.springframework.security.web.FilterChainProxy: INFO