# This is the centralised config for all jobs that need an npm cache
# Currently this is
# - build frontend
# - end2end tests - node (from REPO_ROOT/.gitlab-ci.yml)
.npm-cache-config:
  cache:
    key: "mlreef-node-cache"
    paths:
      - /usr/local/lib/node_modules
      - web/node_modules


build gateway:
  # import the centralised caching configuration for npm caches
  extends: [".base-docker-build", ".npm-cache-config"]
  only:
    changes:
      # changes on specific bin scripts
      - web/bin/ci-build-frontend
      # all files and folders under web/src and web/public
      - web/public/**/*
      - web/src/**/*
      # all files in the web directory
      - web/*
  # This docker version should correspond with the on docker version in the EC2 deployment
  script: |
    docker build --tag "$GATEWAY_IMAGE_PATH" -f web/Dockerfile web  \
      --build-arg CI_COMMIT_REF_SLUG="$CI_COMMIT_REF_SLUG"          \
      --build-arg CI_PIPELINE_ID="$CI_PIPELINE_ID"                  \

    # Get Test coverage report from build image
    docker create -ti --name coverage-container "$GATEWAY_IMAGE_PATH" bash
    # docker cp coverage-container:/usr/share/coverage web/coverage
    docker rm -f coverage-container

    docker build --tag "$GATEWAY_IMAGE_PATH" -f web/Dockerfile web
    docker push "$GATEWAY_IMAGE_PATH"
  artifacts:
    expire_in: 3 days
    paths:
      - web/coverage
